### ISSUE TITLE
New page doesn't scroll to top

### ISSUE THREAD

**Issue by jmgirard** [surveydown-dev/surveydown#104]
### Bug description

I have spread my items across several pages, each of which is taller than screen height (so we must scroll down to navigate). When I scroll down the first page to get to the next page button and click it, it brings me to the next page, but does not scroll me to the top of the next page.

### Steps to reproduce

https://github.com/jmgirard/pid5sd/tree/main/pid5bf
https://jmgirard.shinyapps.io/PID5bf/

### Expected behavior

Upon move to new page, page autoscrolls to top

### Actual behavior

Upon move to new page, page stays scrolls at bottom

### Your environment

```
 version  R version 4.4.1 (2024-06-14 ucrt)
 os       Windows 11 x64 (build 22631)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Chicago
 date     2024-10-01
 rstudio  2024.09.0+375 Cranberry Hibiscus (desktop)
 pandoc   3.4 @ C:/PROGRA~1/Pandoc/ (via rmarkdown)
```

**Comment by jhelvy** [comment]
I've noticed this behavior too, I see it on our [questions demo survey](https://surveydown.shinyapps.io/types/). Any page with many questions to scroll through, you end up focused around the middle of the page when it loads instead of the top. 

We'll address this soon, and we're also working on an auto scrolling feature so that the focus shifts to the next question when you answer one. We'll tackle both at the same time.

**Comment by jhelvy** [comment]
@pingfan-hu do you want to give this a crack?

**Comment by pingfan-hu** [comment]
@jmgirard Hi Jeffrey! I've revised the `auto_scroll` command and it works better now. The updates are listed below:
1. Now if you flip the page, your new page will be scrolled to the top after a 0.2secs delay. If your page loading time is longer than 0.2secs, this scrolling will fail, but it usually won't happen. If it happens please let me know so I'll increase it to 0.3secs.
2. The top scrolling by page flip will always work regardless the value of `auto_scroll`. 
3. As you click on a question, the page will immediately scroll so that this question is moved to the upper middle of the page.
4. If it's a text input question, the auto scrolling will also be triggered by the tab key.

I've tested on it thoroughly and am sure they all work right. Please install our latest version and have a try:
```r
remotes::install_github("surveydown-dev/surveydown", force = TRUE)
```

**Comment by jmgirard** [comment]
This worked well, thanks @pingfan-hu. I also noticed some speedups since the last version.

**Comment by jhelvy** [comment]
Yes, we modified the data writing. It was really slowing things down, so now the data is written on every page turn, which we felt was an appropriate enough compromise between speed and storing the data.

**Comment by pingfan-hu** [comment]
Yes Jeffrey, I've updated the scrolling to make it more robust and more user friendly, and John has optimized the data traffic as well. Now your survey should be faster than before.
To be more specific, now the data transaction will only happen if you turn the page, or if you close the survey. The data transaction is to the complete row instead of one single value. In short, we have more efficient and more secured data traffic.
