### ISSUE TITLE
Conditional showif only works in the same code snippet

### ISSUE THREAD

**Issue by rgmerck** [surveydown-dev/surveydown#108]
### Bug description

Not sure if this is a bug or a feature request. I have noticed that the show_if works well if you put the questions in the same snippet, but the condition does not work if the condition spreads across multiple pages, for example. Do you have an idea on how to deal with a certain condition/ filter, that would be reflected across multiple questions in the survey?

### Steps to reproduce

Add condition in show_if statement
Break down the condition across 2 different questions on different pages

### Expected behavior

question would show or not show based on the show_if statement

### Actual behavior

the filtering condition is not working when the conditions spread across different pages, for example.

### Your environment

Rstudio
Ubuntu 24.04

**Comment by jhelvy** [comment]
This is indeed a bug. I can reproduce with the example below. The  `penguins_other` question will show on page 2 regardless of the answer chosen on page 1. Good news is I'm pretty sure I know why this is occurring. I think we tried to do some performance optimization where it only checked conditions for questions on the same page instead of all questions (which would be slower), but that's causing this problem. Good catch!

`survey.qmd` file:

````qmd
---
format: html
echo: false
warning: false
---

```{r}
library(surveydown)
```

::: {#page1 .sd-page}

```{r}
sd_question(
  type  = 'mc',
  id    = 'penguins',
  label = "Which is your favorite type of penguin?",
  option = c(
    'Adélie'    = 'adelie',
    'Chinstrap' = 'chinstrap',
    'Gentoo'    = 'gentoo',
    'Other'     = 'other'
  )
)

sd_next()
```

:::

::: {#page2 .sd-page}

```{r}
sd_question(
  type  = "text",
  id    = "penguins_other",
  label = "Please specify the other penguin type:"
)

sd_next()
```

:::

::: {#end .sd-page}

```{r}
sd_close()
```

:::
````

`app.R` file:

```r
library(surveydown)

server <- function(input, output, session) {

  sd_show_if(
    input$penguins == "other" ~ "penguins_other"
  )

  # Database designation and other settings
  sd_server(
    use_html = TRUE
  )

}

shiny::shinyApp(ui = sd_ui(), server = server)
```

**Comment by rgmerck** [comment]
Thanks for confirming the bug! Looking forward to the fix @jhelvy

**Comment by jhelvy** [comment]
Okay this should be solved now in v0.3.4. Can you reinstall the package and try again?

**Comment by rgmerck** [comment]
@jhelvy give me one more day, will check soon

**Comment by rgmerck** [comment]
Thanks, I confirm this works now in the latest package version! @jhelvy 
You can close this
