### ISSUE TITLE
sd_close() statement not recognized in the survey file

### ISSUE THREAD

**Issue by rgmerck** [surveydown-dev/surveydown#116]
### Bug description

Hi there,
Using the latest version of the package, i now get a strange warning when running the app.R file:

❌ No sd_close() call found in survey.qmd. This may cause issues with data submission.

Even though my survey.qmd file seems to be properly formatted, and ends with the following:

````
<previous questions above>

```{r}
sd_next(next_page = 'end')
```

:::

::: {#end .sd-page}

## End

This it the last page in the survey.

```{r}
sd_close("Exit Survey")
```

:::

````

I have edited questions in my survey, but not touched anything related to the end statements, so not sure why suddenly this error is popping up. Any idea?

### Expected behavior

Should find that sd_close() is there

### Actual behavior

❌ No sd_close() call found in survey.qmd. This may cause issues with data submission.

### Your environment

Rstudio
Ubuntu 24.04

**Comment by jhelvy** [comment]
This warning was introduced recently after creating the [survey rating](https://surveydown.org/config-options#rating-question) feature. But this warning should only appear if you have the `rate_survey = TRUE` setting in `sd_server()` and you don't have an `sd_close()` function in your survey. Clearly you have a `sd_close()` function, so something must be off with the logic controlling the warning. @pingfan-hu can you look into this?

**Comment by pingfan-hu** [comment]
Yeah I'll take a look at this. Might be a bug inside the `sd_close()` definition.

**Comment by pingfan-hu** [comment]
Hi @rgmerck ! This problem is solved. Now you won't see any error message once you have at least one `sd_close()` function call. Please re-install our package and check it out!

The reason is that our previous logic only checks for the exact no-input `sd_close()` function call. In your case, you have an `"Exit Survey"` as an input, which should be counted as a function call, but our logic was not tolerating that. Now it's okay to have either empty or any user inputs.

btw, if you leave the `sd_close()` function blank, it will by default create a button whose label is `"Exit Survey"`.
