### ISSUE TITLE
Creating Questions Programmatically

### ISSUE THREAD

**Issue by jmgirard** [surveydown-dev/surveydown#82]
I have a lot of items and thus want to create them programmatically. Here is my first attempt, but it didn't work. 

````qmd

---
server: shiny
filters: [surveydown]
---

```{r}
#| context: setup
#| echo: false
#| warning: false
#| message: false

library(surveydown)
library(tidyverse)

sd_setup()

items <- tibble(
  type = "mc",
  id = 1:5,
  label = LETTERS[1:5],
  option = list(c(
    "None" = "0", 
    "A Little" = "1",
    "A lot" = "2"
  ))
)
```

::: {#welcome .sd-page}

```{r}
#| output: asis

ql <- pmap(items, sd_question)
walk(ql, \(x) print(x))
```

```{r}
sd_next(next_page = 'end')
```

:::

::: {#end .sd-page}
This it the last page in the survey
:::

```{r}
#| context: server
...
```
````

The HTML code is created successfully, but is not rendered.
![image](https://github.com/user-attachments/assets/cfff3a63-be1d-479b-ae4b-5a5c9d890b78)

**Comment by jhelvy** [comment]
Interesting, I hadn't thought of this approach, but I can certainly see the value. 

I think the main reason this wasn't working is that the returned item was a list (at least the way I tried it). I didn't try using `print()`, that's not how `sd_question()` was designed to work. So I revised your approach to just use `map()` and then wrapped the output in `tagList()` and it seems to work. Also, note that I had to use `unlist(args$option)` for the `option` argument because it needs to be a vector, not a list. Can you see if this works for you?

````qmd
---
server: shiny
filters: [surveydown]
---

```{r}
#| context: setup
#| echo: false
#| warning: false
#| message: false

library(surveydown)
library(tidyverse)

sd_setup()
```

::: {#welcome .sd-page}

```{r}
items <- tibble(
  type = "mc",
  id = 1:5,
  label = LETTERS[1:5],
  option = list(c(
    "None" = "0", 
    "A Little" = "1",
    "A lot" = "2"
  ))
)

tagList(
  map(1:nrow(items), function(i) {
    args <- items[i, ]
    sd_question(
      id     = as.character(args$id),
      type   = args$type,
      label  = args$label,
      option = unlist(args$option)
    )
  })
)
```

```{r}
sd_next(next_page = 'end')
```

:::

::: {#end .sd-page}

This it the last page in the survey

:::

```{r}
#| context: server

db <- sd_database()
config <- sd_config()
sd_server(
  input   = input,
  output  = output,
  session = session,
  config  = config,
  db      = db
)
```
````

**Comment by jmgirard** [comment]
That worked, thanks! It might be worth building this into a convenience function/wrapper.

**Comment by jhelvy** [comment]
Yeah I like this idea, might for now put it as an example on the [tips page](https://surveydown.org/tips)

**Comment by jhelvy** [comment]
This example is now in the documentation under ["Programmatically generate survey questions"](https://surveydown.org/tips#programmatically-generate-survey-questions)
